const PROD_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
const PROD_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
const PROD_LIST_FAIL = 'PRODUCT_LIST_FAIL';

const PROD_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
const PROD_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
const PROD_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'; 

export { PROD_LIST_REQUEST, PROD_LIST_SUCCESS, PROD_LIST_FAIL, PROD_DETAILS_FAIL, PROD_DETAILS_REQUEST, PROD_DETAILS_SUCCESS };